export const MBTI_SCORES: Record<string, Record<string, number>> = {
  INFJ: {
    INFJ: 97,
    INTJ: 90,
    INTP: 65,
    INFP: 75,
    ENTJ: 55,
    ENFJ: 70,
    ENFP: 100,
    ENTP: 95,
    ISFJ: 50,
    ISTJ: 45,
    ISTP: 30,
    ISFP: 35,
    ESTJ: 40,
    ESFJ: 60,
    ESFP: 85,
    ESTP: 80,
  },
  INTJ: {
    INFJ: 90,
    INTJ: 97,
    INTP: 75,
    INFP: 65,
    ENTJ: 70,
    ENFJ: 55,
    ENFP: 95,
    ENTP: 100,
    ISFJ: 45,
    ISTJ: 50,
    ISTP: 35,
    ISFP: 30,
    ESTJ: 60,
    ESFJ: 40,
    ESFP: 80,
    ESTP: 85,
  },
  ENTJ: {
    INFJ: 55,
    INTJ: 70,
    INTP: 100,
    INFP: 95,
    ENTJ: 97,
    ENFJ: 90,
    ENFP: 65,
    ENTP: 75,
    ISFJ: 40,
    ISTJ: 60,
    ISTP: 85,
    ISFP: 80,
    ESTJ: 50,
    ESFJ: 45,
    ESFP: 30,
    ESTP: 35,
  },
  ENFJ: {
    INFJ: 65,
    INTJ: 55,
    INTP: 95,
    INFP: 100,
    ENTJ: 90,
    ENFJ: 97,
    ENFP: 75,
    ENTP: 65,
    ISFJ: 70,
    ISTJ: 40,
    ISTP: 80,
    ISFP: 80,
    ESTJ: 45,
    ESFJ: 50,
    ESFP: 35,
    ESTP: 35,
  },
  ENFP: {
    INFJ: 100,
    INTJ: 95,
    INTP: 55,
    INFP: 70,
    ENTJ: 60,
    ENFJ: 75,
    ENFP: 97,
    ENTP: 90,
    ISFJ: 85,
    ISTJ: 80,
    ISTP: 40,
    ISFP: 60,
    ESTJ: 30,
    ESFJ: 35,
    ESFP: 50,
    ESTP: 45,
  },
  ENTP: {
    INFJ: 95,
    INTJ: 100,
    INTP: 70,
    INFP: 55,
    ENTJ: 75,
    ENFJ: 65,
    ENFP: 90,
    ENTP: 97,
    ISFJ: 80,
    ISTJ: 85,
    ISTP: 60,
    ISFP: 40,
    ESTJ: 35,
    ESFJ: 45,
    ESFP: 45,
    ESTP: 50,
  },
  INTP: {
    INFJ: 60,
    INTJ: 75,
    INTP: 97,
    INFP: 90,
    ENTJ: 100,
    ENFJ: 95,
    ENFP: 55,
    ENTP: 70,
    ISFJ: 30,
    ISTJ: 35,
    ISTP: 50,
    ISFP: 45,
    ESTJ: 85,
    ESFJ: 80,
    ESFP: 40,
    ESTP: 60,
  },
  INFP: {
    INFJ: 75,
    INTJ: 65,
    INTP: 90,
    INFP: 97,
    ENTJ: 95,
    ENFJ: 100,
    ENFP: 70,
    ENTP: 55,
    ISFJ: 35,
    ISTJ: 30,
    ISTP: 45,
    ISFP: 50,
    ESTJ: 80,
    ESFJ: 85,
    ESFP: 60,
    ESTP: 40,
  },
  ISFJ: {
    INFJ: 50,
    INTJ: 45,
    INTP: 30,
    INFP: 35,
    ENTJ: 40,
    ENFJ: 70,
    ENFP: 85,
    ENTP: 80,
    ISFJ: 97,
    ISTJ: 90,
    ISTP: 65,
    ISFP: 75,
    ESTJ: 55,
    ESFJ: 70,
    ESFP: 100,
    ESTP: 95,
  },
  ISTJ: {
    INFJ: 45,
    INTJ: 50,
    INTP: 35,
    INFP: 30,
    ENTJ: 60,
    ENFJ: 40,
    ENFP: 80,
    ENTP: 85,
    ISFJ: 90,
    ISTJ: 97,
    ISTP: 75,
    ISFP: 65,
    ESTJ: 70,
    ESFJ: 55,
    ESFP: 95,
    ESTP: 100,
  },
  ISTP: {
    INFJ: 30,
    INTJ: 35,
    INTP: 50,
    INFP: 45,
    ENTJ: 85,
    ENFJ: 80,
    ENFP: 40,
    ENTP: 60,
    ISFJ: 65,
    ISTJ: 75,
    ISTP: 97,
    ISFP: 90,
    ESTJ: 100,
    ESFJ: 95,
    ESFP: 55,
    ESTP: 70,
  },
  ISFP: {
    INFJ: 35,
    INTJ: 30,
    INTP: 45,
    INFP: 50,
    ENTJ: 80,
    ENFJ: 85,
    ENFP: 60,
    ENTP: 40,
    ISFJ: 75,
    ISTJ: 65,
    ISTP: 90,
    ISFP: 97,
    ESTJ: 100,
    ESFJ: 95,
    ESFP: 70,
    ESTP: 55,
  },
  ESTJ: {
    INFJ: 40,
    INTJ: 60,
    INTP: 85,
    INFP: 80,
    ENTJ: 50,
    ENFJ: 45,
    ENFP: 30,
    ENTP: 35,
    ISFJ: 55,
    ISTJ: 70,
    ISTP: 100,
    ISFP: 95,
    ESTJ: 97,
    ESFJ: 90,
    ESFP: 65,
    ESTP: 75,
  },
  ESFJ: {
    INFJ: 60,
    INTJ: 40,
    INTP: 80,
    INFP: 85,
    ENTJ: 45,
    ENFJ: 50,
    ENFP: 35,
    ENTP: 45,
    ISFJ: 70,
    ISTJ: 55,
    ISTP: 95,
    ISFP: 100,
    ESTJ: 90,
    ESFJ: 97,
    ESFP: 75,
    ESTP: 65,
  },
  ESFP: {
    INFJ: 85,
    INTJ: 80,
    INTP: 40,
    INFP: 60,
    ENTJ: 30,
    ENFJ: 35,
    ENFP: 50,
    ENTP: 45,
    ISFJ: 100,
    ISTJ: 95,
    ISTP: 55,
    ISFP: 70,
    ESTJ: 65,
    ESFJ: 75,
    ESFP: 97,
    ESTP: 90,
  },
  ESTP: {
    INFJ: 80,
    INTJ: 85,
    INTP: 60,
    INFP: 40,
    ENTJ: 35,
    ENFJ: 50,
    ENFP: 45,
    ENTP: 50,
    ISFJ: 95,
    ISTJ: 100,
    ISTP: 70,
    ISFP: 55,
    ESTJ: 75,
    ESFJ: 65,
    ESFP: 90,
    ESTP: 97,
  },
};

export const calculateSynergy = (
  myMbti: string,
  targetMbti: string,
): number => {
  return MBTI_SCORES[myMbti]?.[targetMbti] ?? 25;
};

export const getTop5Matches = (
  myMbti: string,
  allUserMbtis: { userId: string; mbti: string }[],
) => {
  return allUserMbtis
    .map((user) => ({
      userId: user.userId,
      score: MBTI_SCORES[myMbti]?.[user.mbti] ?? 25,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, 5);
};

export const MBTI_DETAILS: Record<
  string,
  { title: string; about: string[]; traits: string[] }
> = {
  INFJ: {
    title: "The Advocate",
    about: [
      "Quiet and mystical, yet very inspiring.",
      "Tireless idealists with a deep sense of integrity.",
      "Seek to leave a lasting positive impact.",
    ],
    traits: ["Empathetic", "Creative", "Insightful", "Passionate"],
  },
  ENFP: {
    title: "The Campaigner",
    about: [
      "Enthusiastic, creative and sociable free spirits.",
      "Can always find a reason to smile.",
      "Deeply value emotional connections with others.",
    ],
    traits: ["Enthusiastic", "Social", "Idealistic", "Spontaneous"],
  },
  ENTJ: {
    title: "The Commander",
    about: [
      "Bold, imaginative and strong-willed leaders.",
      "Always finding a way – or making one.",
      "Excel at strategic planning and long-term goals.",
    ],
    traits: ["Strategic", "Ambitious", "Confident", "Efficient"],
  },
  INTJ: {
    title: "The Architect",
    about: [
      "Imaginative and strategic thinkers.",
      "Always have a plan for everything.",
      "Enjoy logical analysis and complex problem-solving.",
    ],
    traits: ["Analytical", "Independent", "Logical", "Determined"],
  },
  INFP: {
    title: "The Mediator",
    about: [
      "Poetic, kind and altruistic people.",
      "Always eager to help a good cause.",
      "Value deep relationships with like-minded people.",
    ],
    traits: ["Compassionate", "Creative", "Adaptable", "Whimsical"],
  },
  ENFJ: {
    title: "The Protagonist",
    about: [
      "Charismatic and inspiring leaders.",
      "Able to mesmerize their listeners.",
      "Help others grow and strive for the common good.",
    ],
    traits: ["Charismatic", "Altruistic", "Reliable", "Inspiring"],
  },
  ENTP: {
    title: "The Debater",
    about: [
      "Smart and curious thinkers.",
      "Cannot resist an intellectual challenge.",
      "Energetic, quick-witted, and innovative.",
    ],
    traits: ["Innovative", "Knowledgeable", "Quick-witted", "Energetic"],
  },
  INTP: {
    title: "The Logician",
    about: [
      "Innovative inventors with a thirst for knowledge.",
      "Seek to understand the world through logic.",
      "Quiet, reserved, but deeply analytical.",
    ],
    traits: ["Objective", "Imaginative", "Open-minded", "Intellectual"],
  },
  ESTJ: {
    title: "The Executive",
    about: [
      "Excellent administrators and managers.",
      "Honest, dedicated, and lead with dignity.",
      "Value tradition and orderly environments.",
    ],
    traits: ["Organized", "Dedicated", "Direct", "Pragmatic"],
  },
  ESFJ: {
    title: "The Consul",
    about: [
      "Extraordinarily caring and social people.",
      "Community-minded and eager to help.",
      "Value social harmony and cooperation.",
    ],
    traits: ["Supportive", "Social", "Loyal", "Warm-hearted"],
  },
  ISTJ: {
    title: "The Logistician",
    about: [
      "Practical and fact-minded individuals.",
      "Reliability that cannot be doubted.",
      "Respect rules, tradition, and honesty.",
    ],
    traits: ["Responsible", "Practical", "Orderly", "Honest"],
  },
  ISFJ: {
    title: "The Defender",
    about: [
      "Very dedicated and warm protectors.",
      "Always ready to defend their loved ones.",
      "Possess a deep sense of responsibility.",
    ],
    traits: ["Protective", "Patient", "Detail-oriented", "Humble"],
  },
  ESTP: {
    title: "The Entrepreneur",
    about: [
      "Smart, energetic and very perceptive.",
      "Truly enjoy living on the edge.",
      "Bold, action-oriented, and sociable.",
    ],
    traits: ["Action-oriented", "Bold", "Direct", "Sociable"],
  },
  ESFP: {
    title: "The Entertainer",
    about: [
      "Spontaneous, energetic and enthusiastic.",
      "Life is never boring around them.",
      "Love engaging with others and the spotlight.",
    ],
    traits: ["Playful", "Enthusiastic", "Talkative", "Practical"],
  },
  ISTP: {
    title: "The Virtuoso",
    about: [
      "Bold and practical experimenters.",
      "Masters of all kinds of tools and tech.",
      "Excel at technical troubleshooting.",
    ],
    traits: ["Resourceful", "Observant", "Practical", "Spontaneous"],
  },
  ISFP: {
    title: "The Adventurer",
    about: [
      "Flexible and charming artists.",
      "Always ready to explore and experience new things.",
      "Express themselves freely through creativity.",
    ],
    traits: ["Artistic", "Sensitive", "Quiet", "Flexible"],
  },
};
